### ISSUE TITLE
 ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by shankarsachin** [MichaelBosello/battery-rul-estimation#3]
train_data_test_names = [
    '000-DM-3.0-4019-S', 
    '001-DM-3.0-4019-S', 
    '002-DM-3.0-4019-S', 
    '006-EE-2.85-0820-S', 
    '007-EE-2.85-0820-S', 
    '018-DP-2.00-1320-S', 
    '019-DP-2.00-1320-S',
    '036-DP-2.00-1720-S', 
    '037-DP-2.00-1720-S', 
    '038-DP-2.00-2420-S', 
    '040-DM-4.00-2320-S',
    '042-EE-2.85-0820-S', 
    '045-BE-2.75-2019-S'
]

test_data_test_names = [
    '003-DM-3.0-4019-S',
    '008-EE-2.85-0820-S',
    '039-DP-2.00-2420-S', 
    '041-DM-4.00-2320-S',    
]

dataset.prepare_data(train_data_test_names, test_data_test_names)

Error:

2022/06/28 14:03:12 [DEBUG]: Start preparing data for training: ['000-DM-3.0-4019-S', '001-DM-3.0-4019-S', '002-DM-3.0-4019-S', '006-EE-2.85-0820-S', '007-EE-2.85-0820-S', '018-DP-2.00-1320-S', '019-DP-2.00-1320-S', '036-DP-2.00-1720-S', '037-DP-2.00-1720-S', '038-DP-2.00-2420-S', '040-DM-4.00-2320-S', '042-EE-2.85-0820-S', '045-BE-2.75-2019-S'] and testing: ['003-DM-3.0-4019-S', '008-EE-2.85-0820-S', '039-DP-2.00-2420-S', '041-DM-4.00-2320-S']...
/content/drive/My Drive/battery-state-estimation/battery-state-estimation/data_processing/unibo_powertools_data.py:273: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  cyc_data = np.array(cyc_data)
2022/06/28 14:03:36 [DEBUG]: Finish getting training and testing charge data.
2022/06/28 14:03:48 [DEBUG]: Finish getting training and testing discharge data.
2022/06/28 14:03:48 [DEBUG]: Finish cleaning training and testing charge data.
2022/06/28 14:03:48 [DEBUG]: Finish cleaning training and testing discharge data.
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-6-4db8a2f5dffe>](https://localhost:8080/#) in <module>()
     22 ]
     23 
---> 24 dataset.prepare_data(train_data_test_names, test_data_test_names)

1 frames
[/content/drive/My Drive/battery-state-estimation/battery-state-estimation/data_processing/unibo_powertools_data.py](https://localhost:8080/#) in prepare_data(self, train_names, test_names)
    218 
    219         self.train_discharge_cyc = self.__add_discharge_soc_pars(
--> 220             self.train_discharge_cyc, self.train_charge_cap
    221         )
    222         self.test_discharge_cyc = self.__add_discharge_soc_pars(

[/content/drive/My Drive/battery-state-estimation/battery-state-estimation/data_processing/unibo_powertools_data.py](https://localhost:8080/#) in __add_discharge_soc_pars(self, discharge_cyc, charge_cap)
    311                                      np.zeros(discharge_cyc[i].shape[0])]
    312             discharge_cyc[i][:, -1] = (charge_cap[i][CapacityCols.CHARGING_CAPACITY] - discharge_cyc[i]
--> 313                                        [:, CycleCols.DISCHARGING_CAPACITY]) / charge_cap[i][CapacityCols.CHARGING_CAPACITY]
    314 
    315             # Time remaining to cycle end: (Time of last row in cycle - current time)

ZeroDivisionError: float division by zero

**Comment by MichaelBosello** [comment]
Some tests in the datasets don't have enough data, like '045-BE-2.75-2019-S'. Please refer to the _train_names_ and _test_names_ inside our files. 

The issues you opened (this one and the one about the path) are not issues but usage problems about code you changed, please do your debug yourself. I will not respond anymore to issues containing only the error copy-pasted, please follow the standard rules about GitHub issues if real bugs should be addressed.
