### ISSUE TITLE
what is the version of tensorflow in this code?

### ISSUE THREAD

**Issue by myalos** [MichaelBosello/battery-rul-estimation#4]
Hi, thanks for sharing this great work. The paper and code have inspired me a lot.
I want to reproduce your result, so i would like to ask what version of tensorflow you used in this code? thanks in advance

**Comment by MichaelBosello** [comment]
Hi, TensorFlow 2.7 has been used during the training. I will add this information in the readme.

**Comment by myalos** [comment]
Thanks for reply. I read nasa randomized battery data and didn't figure out the difference between 10k, 20k, and 100k data, and cannot understand the following code
```python
train_x_20k = train_x_20k[:, ::2, :]
test_x_20k = test_x_20k[:, ::2, :]
train_x_100k = train_x_100k[:, ::10, :]
```
The sampling frequency of the same battery in different discharge stages will be different, and the data sampling frequency of 10k, 20k, and 100k in the same stage is basically the same, why should it be processed in this way?

**Comment by myalos** [comment]
In 'RW_Skewed_High_Room_Temp_DataSet_2Post/data/Matlab/RW17' which is the first element in train_names_100k, there exists data missing problem. For example, in the index 52(start from 0) of RW17, they did 90 minutes rest post reference power discharge starting from 06-Aug-2014 01:25:39. The last recorded voltage at that row is 3.697. Then in the next row they did pulsed load(rest) starting from 06-Aug-2014 05:34:40, and the first recorded voltage at that row is 4.199. Obviously the charging row is missing. As a result, the code treat at least two discharge curves as one discharge curve. This seems unreasonable.

**Comment by MichaelBosello** [comment]
10k, 20k, and 100k are the approximate max lengths of the time series (the concatenation of the discharge stages) of the various runs. As the Encoder needs a time series with fixed sizes, the 20k and 100k are sampled to return to ~10k. The series are then cut to 11800. The idea is that the Encoder can generalize to the different sampling frequencies.

For the second question, in RW17 we have an initial sequence of C->R->D->R->C-R->D->...
The code in this repo filters the data keeping only the type D (Discharge) rows, while C (Charge) and R (Rest) are ignored. The RUL is predicted only during discharge and using only discharge data history. The predicted RUL is based on the mAh computed in the reference discharge cycles, regardless of what happened in between (rest, charge, discharge).
As we think the concept of cycles has little meaning in this context, in the paper we propose a RUL based on mAh. Thus, the subdivision in cycles doesn't really have an impact on how the network uses the data. The cycle number in the code is rather used to decide when performing the prediction, as doing it at every timestep would result in unnecessary computation and noisy results.

**Comment by MichaelBosello** [comment]
Readme updated in commit 2dd0836
